# -*- coding: utf-8 -*-
"""Shopify

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJTNRS4xutdGS4yaOyCgWB8R9XtKR6xR
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['shopify_stock (1).csv']))

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['shopify_stock (1).csv']))
display(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
df['date'] = pd.to_datetime(df['date'], utc=True)

plt.figure(figsize=(15, 7))
sns.lineplot(data=df, x='date', y='close')
plt.title('Shopify Stock Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price (USD)')
plt.grid(True)
plt.show()

df['MA20'] = df['close'].rolling(window=20).mean()
df['MA50'] = df['close'].rolling(window=50).mean()

df['MA20'] = df['close'].rolling(window=20).mean()
df['MA50'] = df['close'].rolling(window=50).mean()

plt.figure(figsize=(15, 7))
sns.lineplot(data=df, x='date', y='close', label='Closing Price')
sns.lineplot(data=df, x='date', y='MA20', label='20-Day Moving Average')
sns.lineplot(data=df, x='date', y='MA50', label='50-Day Moving Average')

plt.title('Shopify Stock Closing Price with 20 & 50 Day Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid(True)
plt.show()