# -*- coding: utf-8 -*-
"""Student performanceipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2U2xr0E6Mem0GA7eNOjPTqHPMk8yG6b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")
df

df.info()

df.head()

df.tail()

df.describe()

df.shape

df.columns

df.isnull().sum()

df.duplicated().sum()

score_columns = ['math score', 'reading score', 'writing score']
df[score_columns].describe()

score_columns= ['math score','reading score','writing score']
score_columns
['math score','reading score','writing score']
df.describe()

df[score_columns].mean()

df[score_columns].median()

df[score_columns].mode()

df[score_columns].std()

df[score_columns].quantile(0.25)

df[score_columns].quantile([0.5,0.75])

df["Total Score"]=(df["math score"]+df["reading score"]+df["writing score"])
df

df.columns

df["Percentage"]=(df["Total Score"]/300)*100
df[["Total Score", "Percentage"]].head()

for col in score_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("\n", col)
    print("Lower Limit:", lower)
    print("Upper Limit:", upper)
    print("Number of Outliers:", len(outliers))

print("\nFinal Dataset:")
print(df.head())