# -*- coding: utf-8 -*-
"""data visualization task3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpWxwfMQ3S6xnRYbny9-d_Kb1esiM0rB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
df = pd.read_excel("/content/AAPL.xlsx")
df

df.head()

df.tail()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

df["Daily Price Change"] = df["Close"].diff()

df["Daily Percentage Change"] = df["Close"].pct_change() * 100

print(df.head(10))

print("\nStock Price Analysis:")
print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

print("\nDaily Price Change:")
print(df[["Date", "Close", "Daily Price Change", "Daily Percentage Change"]])

df['Daily Percentage Return'] = df['Close'].pct_change() * 100
print('\nDaily Percentage Return:')
print(df[['Date', 'Close', 'Daily Percentage Return']].head())

biggest_losses = df.sort_values(by='Daily Percentage Return').head(5)
print(biggest_losses[['Date', 'Close', 'Daily Percentage Return']])

biggest_gains = df.sort_values(by='Daily Percentage Return', ascending=False).head(5)
print(biggest_gains[['Date', 'Close', 'Daily Percentage Return']])

average_volume = df['Volume'].mean()
minimum_volume = df['Volume'].min()
maximum_volume = df['Volume'].max()

print(f"Average Trading Volume: {average_volume:,.2f}")
print(f"Minimum Trading Volume: {minimum_volume:,.2f}")
print(f"Maximum Trading Volume: {maximum_volume:,.2f}")

df

plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("APPLE STOCK PRICE ANALYSIS")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()